### ISSUE TITLE
Asset recombination happens on each page refresh

### ISSUE THREAD

**Issue by dbd5** [tQuant/yii2-asset-combiner#1]
Hi @tQuant ,

Your documentation says "... even though the recombination assets into group happens **only when files is changed**."

Somehow, It appears that each time the page is refreshed new compressed files are generated and linked to the page which is different from your documentation.

Is it not better to not reprocess the files if they haven't changed just like you suggested?

Thanks

**Comment by tQuant** [comment]
Hi,
Can't reproduce your problem.
Can you show your config?

**Comment by tQuant** [comment]
Does your boundles registred in the same order every time?
Order matters. If it is different every time, then new files will be generated each time.

**Comment by dbd5** [comment]
Yes - same bundles, static - same order. 

The only thing that may change on page load is a a color profile tied to the current session which is invoked in the init() of the Asset Bundle, but even that won't change unless user makes the change manually. In the case I reported, I made no such changes, I just click browser refresh.

**Here's my config below**

---main.php
`[
    //...
    'as assetCombiner' => [
        'enabled'=>true,

        'class' => 'AssetCombiner\AssetCombinerBehavior',

        // Output path and url
        'outputPath' => '@webroot/assets/ac',
        'outputUrl' => '@web/assets/ac',

        /**
        * Filter to process JS files. If not set, then SimpleJsFilter will be used
        * -- Disable filter here so simple filter will just assemble the
        * -- files we compressed earlier
        */
        // 'filterJs' => ['class' => 'AssetCombiner\filters\UglifyJsFilter', 'sourceMap' => false, 'compress' => false, 'mangle' => false, ],

        /**
        * Filter to process CSS files. If not set, then SimpleCssFilter will be used
        * -- Disable filter here so simple filter will just assemble the
        * -- files we compressed earlier
        */
        // 'filterCss' => 'AssetCombiner\filters\UglifyCssFilter',
    ],

],`

**Comment by dbd5** [comment]
And Asset bundle,


--AppAsset.php

`<?php
use yii\web\AssetBundle;

class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        // ['//fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic','type'=>'text/css'],
        'css/fonts' . (YII_DEBUG ? '.css':'.min.css'),
        'css/style' . (YII_DEBUG ? '.css':'.min.css'),
        // 'css/colors/color9' . (YII_DEBUG ? '.css':'.min.css'),
        'css/custom' . (YII_DEBUG ? '.css':'.min.css'),
    ];

    public $js = [
        'js/plugins' . (YII_DEBUG ?'.js':'.min.js'),
        'js/functions' . (YII_DEBUG ?'.js':'.min.js'),
        'js/app' . (YII_DEBUG ?'.js':'.min.js'),
    ];

    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'common\assets\FontAwesome',
        'yii\web\JqueryAsset',
    ];

    public function init()
    {
        parent::init();
        $this->css[] = '/css/'.Yii::$app->session['color'] . (YII_DEBUG ? '.css':'.min.css').'?v='.time();
    }
}
`

**Comment by tQuant** [comment]
I believe that this is the problem: '?v='.time();
The file name changes with each refresh.
Try to remove it

**Comment by dbd5** [comment]
Yes - you are right, It works now.

Thanks for your great work!
