### ISSUE TITLE
AssetCombiner not working well with theme

### ISSUE THREAD

**Issue by dbd5** [tQuant/yii2-asset-combiner#2]
Hi @tQuant ,

I'm trying to use the console option to combine the files like the documentation says and it is generating the config/assets.php file which I now setup in main.php as follows per documentation; 

`'components' => ['assetManager' => [
            'bundles' => require(__DIR__ . '/assets.php'),
        ],
]`

Somehow when the page loads, the reference to the combined assets are not correct if a theme is active which seems to suggest that the theme may be misconfigured.

However, the theme configuration is trivial

`'components' => ['view' => ['theme' => [
'basePath' => '@frontend/web/t/blue',
                'baseUrl' => '@web/t/blue',
                'pathMap' => [
                    '@frontend/views' => '@frontend/themes/blue',
                ],
],
],
]`

References on the page to dependencies all work fine but the references to the combined assets are wrong, for example

`/t/blue/5b9faf82-151cb111.css`
`/t/blue/fonts/google.css`

The combines CSS file should be;
`/t/blue/assets/ac/5b9faf82-151cb111.css`

 because of where the combiner created the combined files.

Any idea what I could be doing wrong?

**Comment by tQuant** [comment]
Hi @dbd5 ,
Heed your config for asset combiner for console and for web modes.
And config of the original and generated asset

**Comment by dbd5** [comment]
For Console

`'asset-combiner' => [
    'class' => 'AssetCombiner\AssetCombinerController',
    'assetsDir' => '@frontend/themes/blue/assets',
    'assetsNamespace' => 'frontend\themes\blue\assets',
    'bundles' => [
        'yii\web\YiiAsset',
    ],
    'processDependent' => true,
    'aliases' => [
        '@webroot' => '@frontend/web/t/blue',
        '@web' => '/t/blue',
    ],

    'assetManager' => [
        'basePath' => '@webroot',
        'baseUrl' => '@web',
    ],

    'outputPath' => '@webroot',
    'outputUrl' => '@web',

    'recursive' => true,
],
`

For Webmode Integration

`'assetManager' => [
            'bundles' => require(__DIR__ . '/assets.php'),
        ],
`

The generated config file is as follows

`<?php
/**
 * This file is generated by the "yii asset-combiner" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2018-02-04 17:53:01
 */
return [
    'yii\\web\\YiiAsset' => [
        'class' => 'yii\\web\\YiiAsset',
        'basePath' => '/var/www/engage/frontend/web/t/blue/assets/ac',
        'baseUrl' => '/t/blue/assets/ac',
        'js' => [
            'bf359800-34f4b0cd.js',
        ],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [
            'accProcessed' => true,
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
    ],
    'frontend\\themes\\blue\\assets\\AppAsset' => [
        'class' => 'frontend\\themes\\blue\\assets\\AppAsset',
        'basePath' => '/var/www/engage/frontend/web/t/blue/assets/ac',
        'baseUrl' => '/t/blue/assets/ac',
        'js' => [
            '1f05a393-4ba467c2.js',
        ],
        'css' => [
            '5b9faf82-b986c651.css',
        ],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [
            'accProcessed' => true,
        ],
        'depends' => [
            'yii\\web\\YiiAsset',
            'frontend\\assets\\GlobalAsset',
        ],
    ],
    'frontend\\themes\\blue\\assets\\MasonryAsset' => [
        'class' => 'frontend\\themes\\blue\\assets\\MasonryAsset',
        'basePath' => '/var/www/engage/frontend/web/t/blue/assets/ac',
        'baseUrl' => '/t/blue/assets/ac',
        'js' => [
            'd7330de4-39f32d7e.js',
        ],
        'css' => [
            'a08413cd-c26403ac.css',
        ],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [
            'accProcessed' => true,
        ],
        'depends' => [
            'yii\\web\\YiiAsset',
        ],
    ],
];`

**Comment by dbd5** [comment]
Not sure I can reproduce this as of today, closing for now
