### ISSUE TITLE
'processDependent' => true fails

### ISSUE THREAD

**Issue by dbd5** [tQuant/yii2-asset-combiner#3]
Hi @tQuant ,

I get the following error message when I set 'processDependent' => true in console mode.

Creating output bundle 'frontend\assets\GlobalAsset': PHP Warning 'yii\base\ErrorException' with message 'hash_file(/var/www/engage/frontend/web/t/blue/js/g.js): failed to open stream: No such file or directory'

This fails because the path to g.js is wrong because it has been derived from the Assetbundle being processed rather than from the being derived from the $basePath of the Assetbundle referenced.

Please advise if my observation is correct or if there is anything I need to change

Thanks

**Comment by tQuant** [comment]
Hi @dbd5 ,
What is the correct path to the file?
And can you give me you asset combiner config for console mode?

**Comment by dbd5** [comment]
The correct path for the file is;
`/var/www/engage/frontend/web/js/g.js`

Asset Combiner Config
`
'asset-combiner' => [
    'class' => 'AssetCombiner\AssetCombinerController',
    'assetsDir' => '@frontend/themes/blue/assets',
    'assetsNamespace' => 'frontend\themes\blue\assets',
    'bundles' => [
        'yii\web\YiiAsset',
    ],
    'processDependent' => true,
    'aliases' => [
        '@webroot' => '@frontend/web/t/blue',
        '@web' => '/t/blue',
    ],

    'assetManager' => [
        'basePath' => '@webroot',
        'baseUrl' => '@web',
    ],

    'outputPath' => '@webroot',
    'outputUrl' => '@web',

    'recursive' => true,
],
`

The referenced Asset file is as below

`
namespace frontend\assets;
use yii\web\AssetBundle;

class GlobalAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $jsOptions = ['position' => \yii\web\View::POS_END];
    public $css = [
    ];

    public $js = [
        'js/g.js',
        'js/app.js',
    ];

    public $depends = [
        'yii\web\JqueryAsset',
    ];
}
`

**Comment by dbd5** [comment]
Not sure I can reproduce this as of today, closing for now
