### ISSUE TITLE
Prevent asset combination on specific page

### ISSUE THREAD

**Issue by thomas-ddev** [tQuant/yii2-asset-combiner#4]
Hello,

I would like to know if there is a way to prevent the combination of all assets on a specific page? 

I have one asset class per CRUD on my backend, but on one of them the combination breaks some JS/CSS behavior (it's with the yii2fullcalendar widget).

I'm using the default configuration in common/main.php : 

return [ 
...
'assetManager' => [
            'appendTimestamp' => true,
        ],
        'view' => [
            'class' => 'yii\web\View',
            'as assetCombiner' => [
                'class' => 'AssetCombiner\AssetCombinerBehavior',
                'filterJs' => [
                    'class' => 'AssetCombiner\filters\UglifyJsFilter',
                    'sourceMap' => false,
                    'compress' => false,
                    'mangle' => false,
                ],
                'filterCss' => 'AssetCombiner\filters\UglifyCssFilter',
            ],
        ],...
]

Regards,

**Comment by tQuant** [comment]
Hello,
There is an option in version 0.7.5
\AssetCombiner\AssetCombinerBehavior::$exceptActions

Specify actions for which behavior must be disabled

`'exceptActions' => ['site/*', 'auth/login']`

**Comment by thomas-ddev** [comment]
Thanks it works perfectly!
