### ISSUE TITLE
Javascript errors from double minification

### ISSUE THREAD

**Issue by dbd5** [tQuant/yii2-asset-combiner#6]
Hi @tQuant ,

I managed to get rid of most JS errors post from minified bundles after I read somewhere that processing already minified javascript can cause errors by setting up the non minified versions of the JS files in my asset bundles.

It seems that it will be helpful to detect minified files and schedule for combination rather than minification during processing will help. Rather than attempt such detection, it might be simpler to provide an array of already minified files for the user of this plugin to populate so that during processing files that exist in this array are combines rather than processed by Uglify.

Do you think this makes sense?

**Comment by tQuant** [comment]
Hi. Minified files usually contain "min" in the name. I can make them skip minification

**Comment by dbd5** [comment]
Thats far better, thanks

**Comment by tQuant** [comment]
Hi, I added an option "skipMinFiles" to UglifyJsFilter
It will concatinate min files without processing by UglifyJs

**Comment by tQuant** [comment]
Hi, I added an option "skipMinFiles" to UglifyJsFilter
It will concatinate min files without processing by UglifyJs

**Comment by dbd5** [comment]
Great work, will update shortly. Thanks
