### ISSUE TITLE
Processing inlined resources fails

### ISSUE THREAD

**Issue by dbd5** [tQuant/yii2-asset-combiner#7]
Hi @tQuant ,

The error message is **filemtime(): stat failed for /css/alternate.css**

It seems that the plugin attempts to process inlined CSS files but fails because function collectAssetFiles() depends on the line $manager = $this->getAssetManager(); to getAssetPath.

Meanwhile the Yii2 code for inlining css files as below does not provide any information about base path as would a standard asset bundle;
 
$this->registerCssFile("@web/alternate.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
    'media' => 'print',
], 'default-style');

Please advise a work around or fix if my analysis is correct;

Thanks

**Comment by tQuant** [comment]
Hi,
Inline registered files are usually skipped, but when you specify 'depends' - Yii creates bundle, but without basePath/sourcePath.

Fixed in 0.8.2
Such bundles are now ignored. Their files are registered at the end, after all concatinated bundles.

**Comment by Alephel** [comment]
Thanks

**Comment by dbd5** [comment]
Great!
